name: Terraform

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::143063372190:role/GithubTerraform
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform apply -auto-approve
